export const counties = [
  "Bedfordshire",
  "Berkshire",
  "Bristol",
  "Buckinghamshire",
  "Cambridgeshire",
  "Cheshire",
  "Cornwall",
  "Cumbria",
  "Derbyshire",
  "Devon",
  "Dorset",
  "Durham",
  "East Riding of Yorkshire",
  "East Sussex",
  "Essex",
  "Gloucestershire",
  "Greater London",
  "Greater Manchester",
  "Hampshire",
  "Herefordshire",
  "Hertfordshire",
  "Isle of Wight",
  "Kent",
  "Lancashire",
  "Leicestershire",
  "Lincolnshire",
  "Merseyside",
  "Norfolk",
  "North Yorkshire",
  "Northamptonshire",
  "Northumberland",
  "Nottinghamshire",
  "Oxfordshire",
  "Rutland",
  "Shropshire",
  "Somerset",
  "South Yorkshire",
  "Staffordshire",
  "Suffolk",
  "Surrey",
  "Tyne and Wear",
  "Warwickshire",
  "West Midlands",
  "West Sussex",
  "West Yorkshire",
  "Wiltshire",
  "Worcestershire",
  "Isle of Man",
  "County Antrim",
  "County Armagh",
  "County Derry / Londonderry",
  "County Down",
  "County Fermanagh",
  "County Tyrone",
  "Aberdeenshire",
  "Angus",
  "Argyll and Bute",
  "Ayrshire and Arran",
  "Banffshire",
  "Berwickshire",
  "Caithness",
  "City of Aberdeen",
  "City of Dundee",
  "City of Edinburgh",
  "City of Glasgow",
  "Clackmannan",
  "Dumfries",
  "Dunbartonshire",
  "East Lothian",
  "Fife",
  "Inverness",
  "Kincardineshire",
  "Lanarkshire",
  "Midlothian",
  "Moray",
  "Nairn",
  "Orkney",
  "Perth and Kinross",
  "Renfrewshire",
  "Ross and Cromarty",
  "Roxburgh, Ettrick and Lauderdale",
  "Shetland",
  "Stirling and Falkirk",
  "Sutherland",
  "The Stewartry of Kirkcudbright",
  "Tweeddale",
  "West Lothian",
  "Western Isles",
  "Wigtown",
  "Clwyd",
  "Dyfed",
  "Gwent",
  "Gwynedd",
  "Mid Glamorgan",
  "Powys",
  "South Glamorgan",
  "West Glamorgan",
];
