
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `PenguinBar` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model PenguinBar
 * 
 */
export type PenguinBarModel = runtime.Types.Result.DefaultSelection<Prisma.$PenguinBarPayload>

export type AggregatePenguinBar = {
  _count: PenguinBarCountAggregateOutputType | null
  _min: PenguinBarMinAggregateOutputType | null
  _max: PenguinBarMaxAggregateOutputType | null
}

export type PenguinBarMinAggregateOutputType = {
  id: string | null
  joke: string | null
  fact: string | null
  design: string | null
  flavour: string | null
  county: string | null
  shop: string | null
  imageUrl: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type PenguinBarMaxAggregateOutputType = {
  id: string | null
  joke: string | null
  fact: string | null
  design: string | null
  flavour: string | null
  county: string | null
  shop: string | null
  imageUrl: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type PenguinBarCountAggregateOutputType = {
  id: number
  joke: number
  fact: number
  design: number
  flavour: number
  county: number
  shop: number
  imageUrl: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type PenguinBarMinAggregateInputType = {
  id?: true
  joke?: true
  fact?: true
  design?: true
  flavour?: true
  county?: true
  shop?: true
  imageUrl?: true
  createdAt?: true
  updatedAt?: true
}

export type PenguinBarMaxAggregateInputType = {
  id?: true
  joke?: true
  fact?: true
  design?: true
  flavour?: true
  county?: true
  shop?: true
  imageUrl?: true
  createdAt?: true
  updatedAt?: true
}

export type PenguinBarCountAggregateInputType = {
  id?: true
  joke?: true
  fact?: true
  design?: true
  flavour?: true
  county?: true
  shop?: true
  imageUrl?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type PenguinBarAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which PenguinBar to aggregate.
   */
  where?: Prisma.PenguinBarWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PenguinBars to fetch.
   */
  orderBy?: Prisma.PenguinBarOrderByWithRelationInput | Prisma.PenguinBarOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.PenguinBarWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PenguinBars from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PenguinBars.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned PenguinBars
  **/
  _count?: true | PenguinBarCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: PenguinBarMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: PenguinBarMaxAggregateInputType
}

export type GetPenguinBarAggregateType<T extends PenguinBarAggregateArgs> = {
      [P in keyof T & keyof AggregatePenguinBar]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregatePenguinBar[P]>
    : Prisma.GetScalarType<T[P], AggregatePenguinBar[P]>
}




export type PenguinBarGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.PenguinBarWhereInput
  orderBy?: Prisma.PenguinBarOrderByWithAggregationInput | Prisma.PenguinBarOrderByWithAggregationInput[]
  by: Prisma.PenguinBarScalarFieldEnum[] | Prisma.PenguinBarScalarFieldEnum
  having?: Prisma.PenguinBarScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: PenguinBarCountAggregateInputType | true
  _min?: PenguinBarMinAggregateInputType
  _max?: PenguinBarMaxAggregateInputType
}

export type PenguinBarGroupByOutputType = {
  id: string
  joke: string
  fact: string
  design: string
  flavour: string
  county: string
  shop: string
  imageUrl: string | null
  createdAt: Date
  updatedAt: Date
  _count: PenguinBarCountAggregateOutputType | null
  _min: PenguinBarMinAggregateOutputType | null
  _max: PenguinBarMaxAggregateOutputType | null
}

export type GetPenguinBarGroupByPayload<T extends PenguinBarGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<PenguinBarGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof PenguinBarGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], PenguinBarGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], PenguinBarGroupByOutputType[P]>
      }
    >
  >



export type PenguinBarWhereInput = {
  AND?: Prisma.PenguinBarWhereInput | Prisma.PenguinBarWhereInput[]
  OR?: Prisma.PenguinBarWhereInput[]
  NOT?: Prisma.PenguinBarWhereInput | Prisma.PenguinBarWhereInput[]
  id?: Prisma.StringFilter<"PenguinBar"> | string
  joke?: Prisma.StringFilter<"PenguinBar"> | string
  fact?: Prisma.StringFilter<"PenguinBar"> | string
  design?: Prisma.StringFilter<"PenguinBar"> | string
  flavour?: Prisma.StringFilter<"PenguinBar"> | string
  county?: Prisma.StringFilter<"PenguinBar"> | string
  shop?: Prisma.StringFilter<"PenguinBar"> | string
  imageUrl?: Prisma.StringNullableFilter<"PenguinBar"> | string | null
  createdAt?: Prisma.DateTimeFilter<"PenguinBar"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"PenguinBar"> | Date | string
}

export type PenguinBarOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  joke?: Prisma.SortOrder
  fact?: Prisma.SortOrder
  design?: Prisma.SortOrder
  flavour?: Prisma.SortOrder
  county?: Prisma.SortOrder
  shop?: Prisma.SortOrder
  imageUrl?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type PenguinBarWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.PenguinBarWhereInput | Prisma.PenguinBarWhereInput[]
  OR?: Prisma.PenguinBarWhereInput[]
  NOT?: Prisma.PenguinBarWhereInput | Prisma.PenguinBarWhereInput[]
  joke?: Prisma.StringFilter<"PenguinBar"> | string
  fact?: Prisma.StringFilter<"PenguinBar"> | string
  design?: Prisma.StringFilter<"PenguinBar"> | string
  flavour?: Prisma.StringFilter<"PenguinBar"> | string
  county?: Prisma.StringFilter<"PenguinBar"> | string
  shop?: Prisma.StringFilter<"PenguinBar"> | string
  imageUrl?: Prisma.StringNullableFilter<"PenguinBar"> | string | null
  createdAt?: Prisma.DateTimeFilter<"PenguinBar"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"PenguinBar"> | Date | string
}, "id">

export type PenguinBarOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  joke?: Prisma.SortOrder
  fact?: Prisma.SortOrder
  design?: Prisma.SortOrder
  flavour?: Prisma.SortOrder
  county?: Prisma.SortOrder
  shop?: Prisma.SortOrder
  imageUrl?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.PenguinBarCountOrderByAggregateInput
  _max?: Prisma.PenguinBarMaxOrderByAggregateInput
  _min?: Prisma.PenguinBarMinOrderByAggregateInput
}

export type PenguinBarScalarWhereWithAggregatesInput = {
  AND?: Prisma.PenguinBarScalarWhereWithAggregatesInput | Prisma.PenguinBarScalarWhereWithAggregatesInput[]
  OR?: Prisma.PenguinBarScalarWhereWithAggregatesInput[]
  NOT?: Prisma.PenguinBarScalarWhereWithAggregatesInput | Prisma.PenguinBarScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"PenguinBar"> | string
  joke?: Prisma.StringWithAggregatesFilter<"PenguinBar"> | string
  fact?: Prisma.StringWithAggregatesFilter<"PenguinBar"> | string
  design?: Prisma.StringWithAggregatesFilter<"PenguinBar"> | string
  flavour?: Prisma.StringWithAggregatesFilter<"PenguinBar"> | string
  county?: Prisma.StringWithAggregatesFilter<"PenguinBar"> | string
  shop?: Prisma.StringWithAggregatesFilter<"PenguinBar"> | string
  imageUrl?: Prisma.StringNullableWithAggregatesFilter<"PenguinBar"> | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"PenguinBar"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"PenguinBar"> | Date | string
}

export type PenguinBarCreateInput = {
  id?: string
  joke: string
  fact: string
  design: string
  flavour: string
  county: string
  shop: string
  imageUrl?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type PenguinBarUncheckedCreateInput = {
  id?: string
  joke: string
  fact: string
  design: string
  flavour: string
  county: string
  shop: string
  imageUrl?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type PenguinBarUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  joke?: Prisma.StringFieldUpdateOperationsInput | string
  fact?: Prisma.StringFieldUpdateOperationsInput | string
  design?: Prisma.StringFieldUpdateOperationsInput | string
  flavour?: Prisma.StringFieldUpdateOperationsInput | string
  county?: Prisma.StringFieldUpdateOperationsInput | string
  shop?: Prisma.StringFieldUpdateOperationsInput | string
  imageUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PenguinBarUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  joke?: Prisma.StringFieldUpdateOperationsInput | string
  fact?: Prisma.StringFieldUpdateOperationsInput | string
  design?: Prisma.StringFieldUpdateOperationsInput | string
  flavour?: Prisma.StringFieldUpdateOperationsInput | string
  county?: Prisma.StringFieldUpdateOperationsInput | string
  shop?: Prisma.StringFieldUpdateOperationsInput | string
  imageUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PenguinBarCreateManyInput = {
  id?: string
  joke: string
  fact: string
  design: string
  flavour: string
  county: string
  shop: string
  imageUrl?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type PenguinBarUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  joke?: Prisma.StringFieldUpdateOperationsInput | string
  fact?: Prisma.StringFieldUpdateOperationsInput | string
  design?: Prisma.StringFieldUpdateOperationsInput | string
  flavour?: Prisma.StringFieldUpdateOperationsInput | string
  county?: Prisma.StringFieldUpdateOperationsInput | string
  shop?: Prisma.StringFieldUpdateOperationsInput | string
  imageUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PenguinBarUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  joke?: Prisma.StringFieldUpdateOperationsInput | string
  fact?: Prisma.StringFieldUpdateOperationsInput | string
  design?: Prisma.StringFieldUpdateOperationsInput | string
  flavour?: Prisma.StringFieldUpdateOperationsInput | string
  county?: Prisma.StringFieldUpdateOperationsInput | string
  shop?: Prisma.StringFieldUpdateOperationsInput | string
  imageUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PenguinBarCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  joke?: Prisma.SortOrder
  fact?: Prisma.SortOrder
  design?: Prisma.SortOrder
  flavour?: Prisma.SortOrder
  county?: Prisma.SortOrder
  shop?: Prisma.SortOrder
  imageUrl?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type PenguinBarMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  joke?: Prisma.SortOrder
  fact?: Prisma.SortOrder
  design?: Prisma.SortOrder
  flavour?: Prisma.SortOrder
  county?: Prisma.SortOrder
  shop?: Prisma.SortOrder
  imageUrl?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type PenguinBarMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  joke?: Prisma.SortOrder
  fact?: Prisma.SortOrder
  design?: Prisma.SortOrder
  flavour?: Prisma.SortOrder
  county?: Prisma.SortOrder
  shop?: Prisma.SortOrder
  imageUrl?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type StringFieldUpdateOperationsInput = {
  set?: string
}

export type NullableStringFieldUpdateOperationsInput = {
  set?: string | null
}

export type DateTimeFieldUpdateOperationsInput = {
  set?: Date | string
}



export type PenguinBarSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  joke?: boolean
  fact?: boolean
  design?: boolean
  flavour?: boolean
  county?: boolean
  shop?: boolean
  imageUrl?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["penguinBar"]>

export type PenguinBarSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  joke?: boolean
  fact?: boolean
  design?: boolean
  flavour?: boolean
  county?: boolean
  shop?: boolean
  imageUrl?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["penguinBar"]>

export type PenguinBarSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  joke?: boolean
  fact?: boolean
  design?: boolean
  flavour?: boolean
  county?: boolean
  shop?: boolean
  imageUrl?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["penguinBar"]>

export type PenguinBarSelectScalar = {
  id?: boolean
  joke?: boolean
  fact?: boolean
  design?: boolean
  flavour?: boolean
  county?: boolean
  shop?: boolean
  imageUrl?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type PenguinBarOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "joke" | "fact" | "design" | "flavour" | "county" | "shop" | "imageUrl" | "createdAt" | "updatedAt", ExtArgs["result"]["penguinBar"]>

export type $PenguinBarPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "PenguinBar"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    joke: string
    fact: string
    design: string
    flavour: string
    county: string
    shop: string
    imageUrl: string | null
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["penguinBar"]>
  composites: {}
}

export type PenguinBarGetPayload<S extends boolean | null | undefined | PenguinBarDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$PenguinBarPayload, S>

export type PenguinBarCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<PenguinBarFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: PenguinBarCountAggregateInputType | true
  }

export interface PenguinBarDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['PenguinBar'], meta: { name: 'PenguinBar' } }
  /**
   * Find zero or one PenguinBar that matches the filter.
   * @param {PenguinBarFindUniqueArgs} args - Arguments to find a PenguinBar
   * @example
   * // Get one PenguinBar
   * const penguinBar = await prisma.penguinBar.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends PenguinBarFindUniqueArgs>(args: Prisma.SelectSubset<T, PenguinBarFindUniqueArgs<ExtArgs>>): Prisma.Prisma__PenguinBarClient<runtime.Types.Result.GetResult<Prisma.$PenguinBarPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one PenguinBar that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {PenguinBarFindUniqueOrThrowArgs} args - Arguments to find a PenguinBar
   * @example
   * // Get one PenguinBar
   * const penguinBar = await prisma.penguinBar.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends PenguinBarFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, PenguinBarFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__PenguinBarClient<runtime.Types.Result.GetResult<Prisma.$PenguinBarPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first PenguinBar that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PenguinBarFindFirstArgs} args - Arguments to find a PenguinBar
   * @example
   * // Get one PenguinBar
   * const penguinBar = await prisma.penguinBar.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends PenguinBarFindFirstArgs>(args?: Prisma.SelectSubset<T, PenguinBarFindFirstArgs<ExtArgs>>): Prisma.Prisma__PenguinBarClient<runtime.Types.Result.GetResult<Prisma.$PenguinBarPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first PenguinBar that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PenguinBarFindFirstOrThrowArgs} args - Arguments to find a PenguinBar
   * @example
   * // Get one PenguinBar
   * const penguinBar = await prisma.penguinBar.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends PenguinBarFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, PenguinBarFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__PenguinBarClient<runtime.Types.Result.GetResult<Prisma.$PenguinBarPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more PenguinBars that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PenguinBarFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all PenguinBars
   * const penguinBars = await prisma.penguinBar.findMany()
   * 
   * // Get first 10 PenguinBars
   * const penguinBars = await prisma.penguinBar.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const penguinBarWithIdOnly = await prisma.penguinBar.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends PenguinBarFindManyArgs>(args?: Prisma.SelectSubset<T, PenguinBarFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PenguinBarPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a PenguinBar.
   * @param {PenguinBarCreateArgs} args - Arguments to create a PenguinBar.
   * @example
   * // Create one PenguinBar
   * const PenguinBar = await prisma.penguinBar.create({
   *   data: {
   *     // ... data to create a PenguinBar
   *   }
   * })
   * 
   */
  create<T extends PenguinBarCreateArgs>(args: Prisma.SelectSubset<T, PenguinBarCreateArgs<ExtArgs>>): Prisma.Prisma__PenguinBarClient<runtime.Types.Result.GetResult<Prisma.$PenguinBarPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many PenguinBars.
   * @param {PenguinBarCreateManyArgs} args - Arguments to create many PenguinBars.
   * @example
   * // Create many PenguinBars
   * const penguinBar = await prisma.penguinBar.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends PenguinBarCreateManyArgs>(args?: Prisma.SelectSubset<T, PenguinBarCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many PenguinBars and returns the data saved in the database.
   * @param {PenguinBarCreateManyAndReturnArgs} args - Arguments to create many PenguinBars.
   * @example
   * // Create many PenguinBars
   * const penguinBar = await prisma.penguinBar.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many PenguinBars and only return the `id`
   * const penguinBarWithIdOnly = await prisma.penguinBar.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends PenguinBarCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, PenguinBarCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PenguinBarPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a PenguinBar.
   * @param {PenguinBarDeleteArgs} args - Arguments to delete one PenguinBar.
   * @example
   * // Delete one PenguinBar
   * const PenguinBar = await prisma.penguinBar.delete({
   *   where: {
   *     // ... filter to delete one PenguinBar
   *   }
   * })
   * 
   */
  delete<T extends PenguinBarDeleteArgs>(args: Prisma.SelectSubset<T, PenguinBarDeleteArgs<ExtArgs>>): Prisma.Prisma__PenguinBarClient<runtime.Types.Result.GetResult<Prisma.$PenguinBarPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one PenguinBar.
   * @param {PenguinBarUpdateArgs} args - Arguments to update one PenguinBar.
   * @example
   * // Update one PenguinBar
   * const penguinBar = await prisma.penguinBar.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends PenguinBarUpdateArgs>(args: Prisma.SelectSubset<T, PenguinBarUpdateArgs<ExtArgs>>): Prisma.Prisma__PenguinBarClient<runtime.Types.Result.GetResult<Prisma.$PenguinBarPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more PenguinBars.
   * @param {PenguinBarDeleteManyArgs} args - Arguments to filter PenguinBars to delete.
   * @example
   * // Delete a few PenguinBars
   * const { count } = await prisma.penguinBar.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends PenguinBarDeleteManyArgs>(args?: Prisma.SelectSubset<T, PenguinBarDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more PenguinBars.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PenguinBarUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many PenguinBars
   * const penguinBar = await prisma.penguinBar.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends PenguinBarUpdateManyArgs>(args: Prisma.SelectSubset<T, PenguinBarUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more PenguinBars and returns the data updated in the database.
   * @param {PenguinBarUpdateManyAndReturnArgs} args - Arguments to update many PenguinBars.
   * @example
   * // Update many PenguinBars
   * const penguinBar = await prisma.penguinBar.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more PenguinBars and only return the `id`
   * const penguinBarWithIdOnly = await prisma.penguinBar.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends PenguinBarUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, PenguinBarUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PenguinBarPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one PenguinBar.
   * @param {PenguinBarUpsertArgs} args - Arguments to update or create a PenguinBar.
   * @example
   * // Update or create a PenguinBar
   * const penguinBar = await prisma.penguinBar.upsert({
   *   create: {
   *     // ... data to create a PenguinBar
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the PenguinBar we want to update
   *   }
   * })
   */
  upsert<T extends PenguinBarUpsertArgs>(args: Prisma.SelectSubset<T, PenguinBarUpsertArgs<ExtArgs>>): Prisma.Prisma__PenguinBarClient<runtime.Types.Result.GetResult<Prisma.$PenguinBarPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of PenguinBars.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PenguinBarCountArgs} args - Arguments to filter PenguinBars to count.
   * @example
   * // Count the number of PenguinBars
   * const count = await prisma.penguinBar.count({
   *   where: {
   *     // ... the filter for the PenguinBars we want to count
   *   }
   * })
  **/
  count<T extends PenguinBarCountArgs>(
    args?: Prisma.Subset<T, PenguinBarCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], PenguinBarCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a PenguinBar.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PenguinBarAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends PenguinBarAggregateArgs>(args: Prisma.Subset<T, PenguinBarAggregateArgs>): Prisma.PrismaPromise<GetPenguinBarAggregateType<T>>

  /**
   * Group by PenguinBar.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PenguinBarGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends PenguinBarGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: PenguinBarGroupByArgs['orderBy'] }
      : { orderBy?: PenguinBarGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, PenguinBarGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetPenguinBarGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the PenguinBar model
 */
readonly fields: PenguinBarFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for PenguinBar.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__PenguinBarClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the PenguinBar model
 */
export interface PenguinBarFieldRefs {
  readonly id: Prisma.FieldRef<"PenguinBar", 'String'>
  readonly joke: Prisma.FieldRef<"PenguinBar", 'String'>
  readonly fact: Prisma.FieldRef<"PenguinBar", 'String'>
  readonly design: Prisma.FieldRef<"PenguinBar", 'String'>
  readonly flavour: Prisma.FieldRef<"PenguinBar", 'String'>
  readonly county: Prisma.FieldRef<"PenguinBar", 'String'>
  readonly shop: Prisma.FieldRef<"PenguinBar", 'String'>
  readonly imageUrl: Prisma.FieldRef<"PenguinBar", 'String'>
  readonly createdAt: Prisma.FieldRef<"PenguinBar", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"PenguinBar", 'DateTime'>
}
    

// Custom InputTypes
/**
 * PenguinBar findUnique
 */
export type PenguinBarFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PenguinBar
   */
  select?: Prisma.PenguinBarSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PenguinBar
   */
  omit?: Prisma.PenguinBarOmit<ExtArgs> | null
  /**
   * Filter, which PenguinBar to fetch.
   */
  where: Prisma.PenguinBarWhereUniqueInput
}

/**
 * PenguinBar findUniqueOrThrow
 */
export type PenguinBarFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PenguinBar
   */
  select?: Prisma.PenguinBarSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PenguinBar
   */
  omit?: Prisma.PenguinBarOmit<ExtArgs> | null
  /**
   * Filter, which PenguinBar to fetch.
   */
  where: Prisma.PenguinBarWhereUniqueInput
}

/**
 * PenguinBar findFirst
 */
export type PenguinBarFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PenguinBar
   */
  select?: Prisma.PenguinBarSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PenguinBar
   */
  omit?: Prisma.PenguinBarOmit<ExtArgs> | null
  /**
   * Filter, which PenguinBar to fetch.
   */
  where?: Prisma.PenguinBarWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PenguinBars to fetch.
   */
  orderBy?: Prisma.PenguinBarOrderByWithRelationInput | Prisma.PenguinBarOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for PenguinBars.
   */
  cursor?: Prisma.PenguinBarWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PenguinBars from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PenguinBars.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of PenguinBars.
   */
  distinct?: Prisma.PenguinBarScalarFieldEnum | Prisma.PenguinBarScalarFieldEnum[]
}

/**
 * PenguinBar findFirstOrThrow
 */
export type PenguinBarFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PenguinBar
   */
  select?: Prisma.PenguinBarSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PenguinBar
   */
  omit?: Prisma.PenguinBarOmit<ExtArgs> | null
  /**
   * Filter, which PenguinBar to fetch.
   */
  where?: Prisma.PenguinBarWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PenguinBars to fetch.
   */
  orderBy?: Prisma.PenguinBarOrderByWithRelationInput | Prisma.PenguinBarOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for PenguinBars.
   */
  cursor?: Prisma.PenguinBarWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PenguinBars from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PenguinBars.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of PenguinBars.
   */
  distinct?: Prisma.PenguinBarScalarFieldEnum | Prisma.PenguinBarScalarFieldEnum[]
}

/**
 * PenguinBar findMany
 */
export type PenguinBarFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PenguinBar
   */
  select?: Prisma.PenguinBarSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PenguinBar
   */
  omit?: Prisma.PenguinBarOmit<ExtArgs> | null
  /**
   * Filter, which PenguinBars to fetch.
   */
  where?: Prisma.PenguinBarWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PenguinBars to fetch.
   */
  orderBy?: Prisma.PenguinBarOrderByWithRelationInput | Prisma.PenguinBarOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing PenguinBars.
   */
  cursor?: Prisma.PenguinBarWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PenguinBars from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PenguinBars.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of PenguinBars.
   */
  distinct?: Prisma.PenguinBarScalarFieldEnum | Prisma.PenguinBarScalarFieldEnum[]
}

/**
 * PenguinBar create
 */
export type PenguinBarCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PenguinBar
   */
  select?: Prisma.PenguinBarSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PenguinBar
   */
  omit?: Prisma.PenguinBarOmit<ExtArgs> | null
  /**
   * The data needed to create a PenguinBar.
   */
  data: Prisma.XOR<Prisma.PenguinBarCreateInput, Prisma.PenguinBarUncheckedCreateInput>
}

/**
 * PenguinBar createMany
 */
export type PenguinBarCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many PenguinBars.
   */
  data: Prisma.PenguinBarCreateManyInput | Prisma.PenguinBarCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * PenguinBar createManyAndReturn
 */
export type PenguinBarCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PenguinBar
   */
  select?: Prisma.PenguinBarSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the PenguinBar
   */
  omit?: Prisma.PenguinBarOmit<ExtArgs> | null
  /**
   * The data used to create many PenguinBars.
   */
  data: Prisma.PenguinBarCreateManyInput | Prisma.PenguinBarCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * PenguinBar update
 */
export type PenguinBarUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PenguinBar
   */
  select?: Prisma.PenguinBarSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PenguinBar
   */
  omit?: Prisma.PenguinBarOmit<ExtArgs> | null
  /**
   * The data needed to update a PenguinBar.
   */
  data: Prisma.XOR<Prisma.PenguinBarUpdateInput, Prisma.PenguinBarUncheckedUpdateInput>
  /**
   * Choose, which PenguinBar to update.
   */
  where: Prisma.PenguinBarWhereUniqueInput
}

/**
 * PenguinBar updateMany
 */
export type PenguinBarUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update PenguinBars.
   */
  data: Prisma.XOR<Prisma.PenguinBarUpdateManyMutationInput, Prisma.PenguinBarUncheckedUpdateManyInput>
  /**
   * Filter which PenguinBars to update
   */
  where?: Prisma.PenguinBarWhereInput
  /**
   * Limit how many PenguinBars to update.
   */
  limit?: number
}

/**
 * PenguinBar updateManyAndReturn
 */
export type PenguinBarUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PenguinBar
   */
  select?: Prisma.PenguinBarSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the PenguinBar
   */
  omit?: Prisma.PenguinBarOmit<ExtArgs> | null
  /**
   * The data used to update PenguinBars.
   */
  data: Prisma.XOR<Prisma.PenguinBarUpdateManyMutationInput, Prisma.PenguinBarUncheckedUpdateManyInput>
  /**
   * Filter which PenguinBars to update
   */
  where?: Prisma.PenguinBarWhereInput
  /**
   * Limit how many PenguinBars to update.
   */
  limit?: number
}

/**
 * PenguinBar upsert
 */
export type PenguinBarUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PenguinBar
   */
  select?: Prisma.PenguinBarSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PenguinBar
   */
  omit?: Prisma.PenguinBarOmit<ExtArgs> | null
  /**
   * The filter to search for the PenguinBar to update in case it exists.
   */
  where: Prisma.PenguinBarWhereUniqueInput
  /**
   * In case the PenguinBar found by the `where` argument doesn't exist, create a new PenguinBar with this data.
   */
  create: Prisma.XOR<Prisma.PenguinBarCreateInput, Prisma.PenguinBarUncheckedCreateInput>
  /**
   * In case the PenguinBar was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.PenguinBarUpdateInput, Prisma.PenguinBarUncheckedUpdateInput>
}

/**
 * PenguinBar delete
 */
export type PenguinBarDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PenguinBar
   */
  select?: Prisma.PenguinBarSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PenguinBar
   */
  omit?: Prisma.PenguinBarOmit<ExtArgs> | null
  /**
   * Filter which PenguinBar to delete.
   */
  where: Prisma.PenguinBarWhereUniqueInput
}

/**
 * PenguinBar deleteMany
 */
export type PenguinBarDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which PenguinBars to delete
   */
  where?: Prisma.PenguinBarWhereInput
  /**
   * Limit how many PenguinBars to delete.
   */
  limit?: number
}

/**
 * PenguinBar without action
 */
export type PenguinBarDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PenguinBar
   */
  select?: Prisma.PenguinBarSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PenguinBar
   */
  omit?: Prisma.PenguinBarOmit<ExtArgs> | null
}
